name: Linux Build Artifact
concurrency:
  group: linux_build_artifact_${{ github.ref }}
  cancel-in-progress: true
on:
  # trigger manually
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - "**.rst"
      - "docs/**"
  push:
    paths-ignore:
      - "**.rst"
      - "docs/**"

env:
  IMAGE_TAG: amithgeorge/javet-linux-dev:gradle-deps-latest

jobs:
  javet_linux_x86_64:
    name: Javet Linux x86_64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Build the artifact
        run: |
          docker run --rm --name javet-dev-local --volume $(pwd):/Javet --workdir /Javet ${{ env.IMAGE_TAG }} /Javet/scripts/shell/build_javet_artifacts

      - name: Upload the artifact
        uses: actions/upload-artifact@v3
        with:
          name: javet-linux-x86_64
          path: build/libs/javet*.jar
